# Reading the data

In [1]:
import pandas as pd
df = pd.read_excel(r'C:\Users\Mirnalini\Relap.xlsx',na_values=['BLANK'])
df_c = df.copy()

In [2]:

#pd.options.display.max_columns=150
#df.info()
#df.describe()
#pd.options.display.max_rows=150
#df.dtypes
#df_c.columns
#df.sample()
#import matplotlib.pyplot as plt

#aa.hist(bins=10)
#plt.show()

In [2]:
#Mapping Yes as 1 and No as 0
rein_dict = {"Yes": 1 , "No" : 0}
def func(x,rein_dict):
    try:
        tmp = rein_dict[x]
        return(tmp)
    except:
        return('default')
    
df['Reinstated'] = df['Reinstated'].map(lambda x : func(x,rein_dict))

In [4]:
df['Reinstated'].head()
#rein_dict["Yes"]

0    0
1    0
2    0
3    0
4    1
Name: Reinstated, dtype: int64

# Train Test Split

In [3]:
from sklearn.model_selection import train_test_split
X = df.drop(['Reinstated'],axis=1)
y = df['Reinstated']
X_train,X_valid,y_train,y_valid = train_test_split(X,y,train_size=0.8,test_size=0.2,random_state=0)

# Handling Nan/Missing values

Column Level

In [4]:
## Method 1 - Missing value - Dropping col based on count of missing values
missing_df = df.isnull().sum(axis=0).reset_index()
missing_df.columns=['column name','missing value']
pd.options.display.max_rows=110
missing_df = missing_df[missing_df['missing value']  > 44]
missing_df.sort_values(by='missing value')
missing_df

X_train.drop(missing_df['column name'],axis=1,inplace=True)
X_valid.drop(missing_df['column name'],axis=1,inplace=True)
#X_valid

C:\Users\Mirnalini\Anaconda3\lib\site-packages\pandas\core\frame.py:4169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [5]:
#Filling missing values for object only columns

s= (X_train.dtypes=='object')
obj_cols = list(s[s].index) #s[s] returns only True variables alone
len(obj_cols)

def missf(X_tra,X_val):
    for col in obj_cols:
        X_tra.fillna('unknown',inplace=True)
        X_val.fillna('unknown',inplace=True)
        
#X_train_c = X_train.copy()
#X_valid_c = X_valid.copy()

missf(X_train,X_valid)

X_train.fillna(0,inplace=True)
X_valid.fillna(0,inplace=True)
X_valid.head()


#miss_df = df.isnull().sum(axis=0).reset_index()
#miss_df.columns=['column name','missing value']
#pd.options.display.max_rows=110
#miss_df = missing_df[missing_df['missing value']  > 44]
#miss_df.sort_values(by='missing value')
#miss_df

#a = miss_df['column name']

#miss_cols = list(a)

#miss_cols_obj = [col for col in obj_cols if col in miss_cols]
#miss_cols_obj

#for col in miss_cols_obj:
 
    #aa = X_train[miss_cols_obj]
    
#aa.fillna("unknow")

C:\Users\Mirnalini\Anaconda3\lib\site-packages\pandas\core\frame.py:4322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

,ID,INSURANCE_TYPE,SEX,POL_ANNIV_DTE,AGE_AT_ISSUE,SERIES_CDE,PLAN_CDE,NO_TERR_NUM,AGENT_WRITING_CODE,PREMIUM_MODE,...,ADDN_D_D_THIS_YEAR,ADDN_D_D_NEXT_YEAR,ADDN_D_YEAR_AFTR,POLICY_INDEX,ILL_DIV_SCAL_YEAR,PURE_ENDOWMWNT,YTD_PREMIUMS_PAID,UNDERWRITE_AMT,CUM_DUS_TOT_AMT,END_LST_YR_AV_AMT
45,TA,1,M,19960521,42,52,501,109,2,4,...,0.00000,0.00000,0.00000,0,0,0,0,0,0,0.0
118,OAAAA,1,M,19810423,39,41,177,74,1,1,...,-0.03767,-0.03794,-0.03814,0,0,0,2893,0,0,0.0
16,Q,2,F,20160801,31,46,700,126,1,6,...,0.00000,0.00000,0.00000,0,0,0,0,0,0,0.0
56,EAA,1,M,20000802,46,53,501,25,1,6,...,0.00000,0.00000,0.00000,0,0,0,0,0,0,0.0
22,W,2,M,19911029,31,29,700,60,1,6,...,0.00000,0.00000,0.00000,0,0,0,0,0,0,0.0

In [6]:
#Method 2
#aa = df.isna().sum(axis=0)
#import numpy as np
#num_e = len(df)
#thr = 0.50
#keep_vars = np.array(df.columns[(aa) <= thr * num_e])
#keep_vars.shape
#new_var = [ele for ele in df.columns if ele in keep_vars]
#df = df[list(new_var)]
#df.head()
pd.options.display.max_columns=100
X_train.describe()

,INSURANCE_TYPE,POL_ANNIV_DTE,AGE_AT_ISSUE,SERIES_CDE,PLAN_CDE,NO_TERR_NUM,AGENT_WRITING_CODE,PREMIUM_MODE,FACE_AMOUNT,PREM_PAID_TO_DTE,DIVIDEND,DIVIDEND_LAST_YEAR,DIVIDEND_Y_DTE,UNDWRT_BASIS_AMT,MODAL_PREMIUM,SELECTION_CODE,POL_SELECTION_DTE,MATURITY_YEAR,PREMIUM_ADJUSTMENT,CUMULATIVE_PREMS,GROSS_ANN_PRM_RATE,GROSS_AN_TRM_BAND_RT,NET_ANN_PREM_RATE,CUM_DIVIDENDS,CASH_VALUE_INC,PREMIUM_FACE,PROG_APPRAISEL_CDE,NET_ANN_PREM_RATE2,END_LST_YR_CV_AMT,RESERVE_RATE,DAILY_DIFF_PAST_YR,DAILY_DIFF_THIS_YR,DAILY_DIFF_NEXT_YR,DAILY_DIFF_YR_AFTR,ADDITIONS_BALANCE,ADDITIONS_RES_RATE,ADDN_D_D_PAST_YEAR,ADDN_D_D_THIS_YEAR,ADDN_D_D_NEXT_YEAR,ADDN_D_YEAR_AFTR,POLICY_INDEX,ILL_DIV_SCAL_YEAR,PURE_ENDOWMWNT,YTD_PREMIUMS_PAID,UNDERWRITE_AMT,CUM_DUS_TOT_AMT,END_LST_YR_AV_AMT
count,114.000000,1.140000e+02,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,1.140000e+02,1.140000e+02,114.000000,114.000000,114.000000,1.140000e+02,114.000000,114.000000,1.140000e+02,114.000000,114.0,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,1.140000e+02,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.0,114.000000,1.140000e+02,114.0,114.000000
mean,1.166667,1.997961e+07,32.956140,45.359649,467.640351,70.438596,0.789474,3.824561,2.459557e+05,2.010628e+07,495.859649,452.263158,2010.043860,6.436975e+05,260.473684,72.114035,2.012567e+07,2037.280702,0.0,11683.552632,9.771930,2.894737,0.894737,2580.500000,372.605263,2.420031e+05,1.464912,0.464825,1.621140,36.026316,-0.001832,-0.001733,-0.001985,-0.001633,7968.350877,89.596491,-0.005478,-0.006195,-0.006236,-0.006268,20.526316,70.815789,0.0,227.947368,1.006974e+05,0.0,2.050789
std,0.374323,1.232666e+05,9.901632,9.547392,192.340182,35.942440,0.587083,2.282080,3.434923e+05,5.541474e+04,1208.087012,1128.067798,5.633953,1.659466e+06,582.234636,41.784902,6.407625e+04,15.223706,0.0,21801.539871,20.795692,19.622711,3.185610,8721.701487,1264.267507,3.431361e+05,2.803853,2.328064,17.309042,125.780358,0.010112,0.010537,0.010611,0.012065,21743.242894,204.207153,0.014824,0.014808,0.015069,0.015359,155.230757,373.000879,0.0,1298.647042,3.117849e+05,0.0,21.896440
min,1.000000,1.979063e+07,0.000000,24.000000,100.000000,1.000000,0.000000,1.000000,0.000000e+00,2.001061e+07,0.000000,0.000000,2001.000000,0.000000e+00,0.000000,3.000000,2.002072e+07,2012.000000,0.0,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-0.063480,-0.065670,-0.067970,-0.070360,0.000000,0.000000,-0.063480,-0.065670,-0.067970,-0.070360,0.000000,0.000000,0.0,0.000000,0.000000e+00,0.0,0.000000
25%,1.000000,1.986082e+07,29.000000,37.000000,501.000000,42.250000,0.000000,1.000000,7.071000e+03,2.006111e+07,0.000000,0.000000,2005.250000,5.000000e+04,0.000000,31.250000,2.008033e+07,2024.250000,0.0,1351.750000,1.000000,0.000000,0.000000,0.000000,0.000000,7.071000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000e+00,0.0,0.000000
50%,1.000000,2.000076e+07,34.000000,46.000000,501.000000,75.000000,1.000000,4.000000,1.000000e+05,2.010027e+07,19.500000,0.000000,2009.000000,1.993980e+05,0.000000,99.000000,2.011052e+07,2035.500000,0.0,3046.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000e+00,0.0,0.000000
75%,1.000000,2.006032e+07,38.000000,55.000000,512.000000,101.000000,1.000000,6.000000,3.000000e+05,2.015770e+07,230.250000,185.250000,2016.000000,5.000000e+05,147.500000,99.000000,2.017814e+07,2046.750000,0.0,10361.250000,10.000000,1.000000,0.000000,269.750000,0.000000,2.950000e+05,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000e+00,0.0,0.000000
max,2.000000,2.020051e+07,50.000000,56.000000,985.000000,130.000000,2.000000,8.000000,2.000000e+06,2.021072e+07,8237.000000,7407.000000,2020.000000,1.355000e+07,2615.000000,99.000000,2.025072e+07,2079.000000,0.0,126825.000000,154.000000,208.000000,21.000000,55394.000000,9849.000000,2.000000e+06,9.000000,17.430000,184.810000,684.000000,0.022520,0.024740,0.027640,0.051510,105602.000000,725.000000,0.037890,0.022770,0.026220,0.030520,1564.000000,2020.000000,0.0,13347.000000,2.000000e+06,0.0,233.790000

Row Level

There is no row which has more than 5 nan values; so need not remove

In [7]:
row_df = X_train.isnull().sum(axis=1).reset_index()
row_df.columns = ['Index','Row_count']
#row_df.index.name = 'Index'
row_df.sort_values(by='Row_count',ascending=False).head()

    Index  Row_count
0     126          0
85     82          0
83    129          0
82     49          0
81     29          0

# Handling Datatype value

In [8]:
d_df = X_train.dtypes.reset_index()
d_df.columns = ["Count","Column Type"]
d_df.groupby("Column Type").aggregate("count").reset_index()

  Column Type  Count
0       int64     36
1     float64     11
2      object     14

# Handling Constant value

This removes the features which has the total number of unique values of 1 (Say if the feature has either 0/1/2 as the only value)

In [9]:
cons_df = X_train.nunique().reset_index()
cons_df.columns = ['col_name','unique_count']
cons_df = cons_df[cons_df['unique_count'] == 1].reset_index()
cons_df

   index            col_name  unique_count
0     29  PREMIUM_ADJUSTMENT             1
1     56      PURE_ENDOWMWNT             1
2     59     CUM_DUS_TOT_AMT             1

In [10]:
X_train = X_train.drop(cons_df['col_name'],axis=1)
X_valid = X_valid.drop(cons_df['col_name'],axis=1)

# Variance Threshold

Variance will be zero if the values are all same; Similar to unique .. True indicated that the features need not be removed as its variance is greater than Zero

In [11]:
#df1 = df.select_dtypes(include='int64') 

#from sklearn.feature_selection import VarianceThreshold
#var_obj = VarianceThreshold(threshold=0)
#var_obj.fit(df1)
#var_obj.get_support()

X_train.drop(columns=['ID'],inplace=True)
X_valid.drop(columns=['ID'],inplace=True)
X_train.head()

,INSURANCE_TYPE,SEX,POL_ANNIV_DTE,AGE_AT_ISSUE,SERIES_CDE,PLAN_CDE,NO_TERR_NUM,AGENT_WRITING_CODE,PREMIUM_MODE,MEDICAL_CODE,NONFORFEITURE_OPTN,DIVIDEND_OPT_CDE,FACE_AMOUNT,POLICY_STATUS,SPECIAL_HANDLING,STATE_OF_RESID_CDE,PREM_PAID_TO_DTE,PREMIUM_STATUS,DIVIDEND,DIVIDEND_LAST_YEAR,DIVIDEND_Y_DTE,INT_RATE_CDE,UNDERWRITING_CODE,UNDWRT_BASIS_AMT,MODAL_PREMIUM,SELECTION_CODE,POL_SELECTION_DTE,MATURITY_YEAR,CUMULATIVE_PREMS,GROSS_ANN_PRM_RATE,GROSS_AN_TRM_BAND_RT,NET_ANN_PREM_RATE,CUM_DIVIDENDS,CASH_VALUE_INC,LARGE_RISK_CODE,PROPOSAL_CODE,PREMIUM_FACE,PROG_APPRAISEL_CDE,NET_ANN_PREM_RATE2,SMOKER_CODE,END_LST_YR_CV_AMT,RESERVE_RATE,DAILY_DIFF_PAST_YR,DAILY_DIFF_THIS_YR,DAILY_DIFF_NEXT_YR,DAILY_DIFF_YR_AFTR,ADDITIONS_BALANCE,ADDITIONS_RES_RATE,ADDN_D_D_PAST_YEAR,ADDN_D_D_THIS_YEAR,ADDN_D_D_NEXT_YEAR,ADDN_D_YEAR_AFTR,POLICY_INDEX,ILL_DIV_SCAL_YEAR,YTD_PREMIUMS_PAID,UNDERWRITE_AMT,END_LST_YR_AV_AMT
126,1,F,19840709,31,31,501,81,2,4,B,G,G,500000,Z,A,TN,20080109,A,97,87,2007,N,N,50000,0,99,20091009,2023,3534,6,7,0,260,0,0,K,50000,1,0.0,N,0.0,0,0.00000,0.00000,0.0,0.0,0,0,0.00000,0.00000,0.00000,0.00000,0,0,0,0,0.0
2,2,F,20031021,29,46,700,10,1,6,C,unknown,G,1260,Z,A,VA,20100821,I,102,83,2009,unknown,C,0,0,99,20120821,2039,2715,20,0,0,336,0,unknown,unknown,1260,0,0.0,N,0.0,0,0.00000,0.00000,0.0,0.0,0,0,0.00000,0.00000,0.00000,0.00000,0,0,0,0,0.0
27,1,F,19860826,28,36,599,45,0,8,A,A,I,32632,Z,A,VT,20140626,N,0,0,2016,N,N,200000,0,99,20220203,2017,8515,0,0,0,0,0,0,K,32632,1,0.0,N,0.0,3,0.02112,0.02273,0.0,0.0,0,0,0.00000,0.00000,0.00000,0.00000,0,0,0,0,0.0
125,1,M,19811228,32,41,177,56,1,1,A,A,B,0,A,A,NJ,20141228,A,3235,3035,2013,Q,S,150861,2276,3,20141208,2039,79102,0,0,0,0,4107,1,K,0,9,0.0,S,0.0,0,0.00000,0.00000,0.0,0.0,61001,589,-0.03816,-0.03814,-0.03803,-0.03789,0,0,2376,0,0.0
10,2,M,20080521,34,46,700,79,1,4,C,unknown,G,299,Z,A,RI,20100821,I,164,0,2010,unknown,S,0,0,99,20120821,2039,1231,26,0,0,164,0,unknown,unknown,299,0,0.0,1,0.0,0,0.00000,0.00000,0.0,0.0,0,0,0.00000,0.00000,0.00000,0.00000,0,0,0,0,0.0

# Mean Aboslute error function

In [ ]:
#Retrieving object datatype alone

s= (X_train.dtypes=='object')
obj_cols = list(s[s].index) #s[s] returns only True variables alone
len(obj_cols)


#Measure quality of each approach

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

def score_ds(X_trains,X_valids,y_trains,y_valids):
    model = RandomForestRegressor(n_estimators=200,random_state=0)
    model.fit(X_trains,y_trains)
    pred = model.predict(X_valids)
    return mean_absolute_error(y_valids,pred)


# M1 - Removing Object features

In [15]:
from sklearn.metrics import median_absolute_error
#M1 - Removing Object features
drop_X_train = X_train.select_dtypes(exclude=['object'])
drop_X_valid = X_valid.select_dtypes(exclude=['object'])
print(score_ds(drop_X_train,drop_X_valid,y_train,y_valid))

0.14896551724137935

# M2 - Label Encoding

In [24]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
#label_X_train = X_train.copy()
#label_X_valid = X_valid.copy()

    
#print(cl) 
enc = {col : LabelEncoder() for col in obj_cols}

for col in obj_cols:

    label_X_train = enc[col].fit_transform(X_train[col])
    #rint(label_X_train)
    label_X_valid = enc[col].fit_transform(X_valid[col])""
    #rint(label_X_valid)
    
print(score_ds(label_X_train,label_X_valid,y_train,y_valid))

SyntaxError: invalid syntax (<ipython-input-24-0836ee1b82bb>, line 14)

# M3 - Onehot coding

In [18]:
from sklearn.preprocessing import OneHotEncoder
oh_enc = OneHotEncoder()
X_ext = X_ext.apply(lambda col:oh_enc.fit_transform(col.astype(str)),axis=0,result_type='expand')
#oh_valid = pd.DataFrame(oh_enc.fit_transform(X_ext))

X_ext

NameError: name 'X_ext' is not defined

# M4 - Target coding

# Dependent variable - Balanced/Not check

In [17]:

import matplotlib as plt
y_train.hist(bins=10)

In [66]:
enc = {col : LabelEncoder() for col in obj_cols}

for col in  Xobj_df.columns:
    Xobj_df[col] = Xobj_df[col].astype(str)
    label_X_train = enc[col].fit_transform(Xobj_df[col])
    label_X_valid = enc[col].fit_transform(Xobj_df[col])
label_X_ = np.array(label_X_train).reshape((1,-1))
label_V_ = np.array(label_X_valid).reshape((1,-1))
#print(label_X_)
    #
    #rint(label_X_valid)
    
print(score_ds(label_X_,label_V_,y_t1,y_t2))

C:\Users\Mirnalini\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

ValueError: y_true and y_pred have different number of output (29!=114)

In [46]:
Xobj_df

,SEX,MEDICAL_CODE,NONFORFEITURE_OPTN,DIVIDEND_OPT_CDE,POLICY_STATUS,SPECIAL_HANDLING,STATE_OF_RESID_CDE,PREMIUM_STATUS,INT_RATE_CDE,UNDERWRITING_CODE,LARGE_RISK_CODE,PROPOSAL_CODE,SMOKER_CODE
126,F,B,G,G,Z,A,TN,A,N,N,0.0,K,N
2,F,C,unknown,G,Z,A,VA,I,unknown,C,unknown,unknown,N
27,F,A,A,I,Z,A,VT,N,N,N,0.0,K,N
125,M,A,A,B,A,A,NJ,A,Q,S,1.0,K,S
10,M,C,unknown,G,Z,A,RI,I,unknown,S,unknown,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,M,C,unknown,G,Z,A,IL,I,unknown,S,unknown,unknown,1
103,F,C,G,G,Z,A,AZ,I,N,22,1.0,K,1
67,M,C,G,G,Z,A,PA,I,N,N,1.0,K,N
117,M,C,A,B,A,A,FL,N,H,S,0.0,K,unknown
47,M,A,G,G,Z,A,IL,I,N,N,0.0,K,N

In [59]:
y_train.shape

(114,)

In [60]:
label_X_.shape

(1, 114)

In [61]:
label_V_.shape

(1, 114)

In [63]:
y_t1 = np.array(y_train).reshape((1,-1))

In [64]:
y_t1.shape

(1, 114)

In [65]:
y_t2 = np.array(y_valid).reshape((1,-1))

In [67]:
y_t2.shape

(1, 29)