In [1]:
import pandas as pd
train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv",sep=',')
train.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [2]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
    train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
b = train.dtypes[train.dtypes == 'int64'].index
train[b].describe()

       PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [7]:
sorted(train['Name'][:1])

['Braund, Mr. Owen Harris']

In [68]:
char_cabin = (train['Cabin']).astype(str)
new_cabin = [i[0] for i in char_cabin]
new_cabin1 = pd.Categorical(new_cabin)
train['new_cabin1'] = new_cabin1
train['new_cabin1']
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_cabin1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,n
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,n
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,n
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,n
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,E
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,n
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,n
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,n
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,G
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,C
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,n
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,n
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,n
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,n
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,n
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,n
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,n
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,n
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S,n
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,D
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,n
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,A
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,n
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,n
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,n
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,n
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S,n
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,D
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,n
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S,n
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S,n
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,n
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,A
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,n
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,n
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S,n
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,D
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,B
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,n
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,n
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,n
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S,n
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S,n
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,n
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,n
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S,n
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,n
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,n
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,n
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,n
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,n
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,B
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,n
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,n

In [36]:
Cabin_1

nan

In [76]:

Sex_1 = [j[0] for j in train['Sex']]
train['Sex_1'] = Sex_1
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_cabin1,Sex_1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,n,m
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,f
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,n,f
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C,f
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,n,m
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,n,m
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,E,m
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,n,m
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,n,f
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,n,f
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,G,f
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,C,f
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,n,m
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,n,m
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,n,f
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,n,f
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,n,m
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,n,m
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,n,f
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,n,f
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S,n,m
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,D,m
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,n,f
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,A,m
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,n,f
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,n,f
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,n,m
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,C,m
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,n,f
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S,n,m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S,n,m
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,D,f
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,n,f
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S,n,m
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S,n,f
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,n,f
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,A,m
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,n,m
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,n,m
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S,n,m
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,D,f
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,B,m
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,n,m
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,n,f
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,n,f
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S,n,m
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S,n,m
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,n,m
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,C,f
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,n,f
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S,n,m
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,n,f
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,n,m
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,n,m
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,n,f
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,n,m
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,B,f
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,n,f
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,C,m
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,n,m

In [77]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [85]:
import numpy as np
np.where(train['Age'].isnull() == True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),)

In [101]:
a = np.where(train['Fare'] == max(train['Fare']))
a

(array([258, 679, 737], dtype=int64),)

In [109]:
train.iloc[a][['Name','Age']]

                                   Name   Age
258                    Ward, Miss. Anna  35.0
679  Cardeza, Mr. Thomas Drake Martinez  36.0
737              Lesurer, Mr. Gustave J  35.0

In [117]:
a1 = np.where(train['Age'] == min(train['Age']))
train.iloc[a1][['Name','Cabin']]

                                Name Cabin
803  Thomas, Master. Assad Alexander   NaN

In [121]:
train['conx'] = train['Age'] + train['Pclass']
train['conx']

0      25.0
1      39.0
2      29.0
3      36.0
4      38.0
5       NaN
6      55.0
7       5.0
8      30.0
9      16.0
10      7.0
11     59.0
12     23.0
13     42.0
14     17.0
15     57.0
16      5.0
17      NaN
18     34.0
19      NaN
20     37.0
21     36.0
22     18.0
23     29.0
24     11.0
25     41.0
26      NaN
27     20.0
28      NaN
29      NaN
       ...
861    23.0
862    49.0
863     NaN
864    26.0
865    44.0
866    29.0
867    32.0
868     NaN
869     7.0
870    29.0
871    48.0
872    34.0
873    50.0
874    30.0
875    18.0
876    23.0
877    22.0
878     NaN
879    57.0
880    27.0
881    36.0
882    25.0
883    30.0
884    28.0
885    42.0
886    29.0
887    20.0
888     NaN
889    27.0
890    35.0
Name: conx, Length: 891, dtype: float64

In [129]:
li = [1,5,3]
ar = np.array(li)
se= pd.Series(ar,index=['a','b','c'])
se['a']

1

In [1]:
pwd()

'C:\\Users\\Mirnalini'

In [27]:
#Check whether parent dir exist
import os
path = 'C:\\Users\\Mirnalini\\Parent'
if (os.path.isdir(path) == True) :
    path = 'C:\\Users\\Mirnalini\\Parent\\Child1'
    if (os.path.isdir(path) == True) :
        print("Inside Child1")
        path = 'C:\\Users\\Mirnalini\\Parent\\Child1\\aaa.txt'
        #Reading Text File
        with open(path,'r') as f1:
            data1 = f1.read()
            print("Reading txt file 1" , data1)
        #writing Text File
        with open('aaa1.txt','w') as f11:
            f11.write(data1)

Inside Child1
Reading txt file 1 a
aa
aaa
aaaa
aaaaa

In [54]:
#Reading Word document
import docx
path = 'C:\\Users\\Mirnalini\\Parent\\Child1\\Aa.docx'
data1 = docx.Document(path)
for i in data1.paragraphs:
    a = i.text
    
      
#writing word document
data2 = docx.Document()
data2.add_paragraph(a)
data2.save('Aaaa.docx')

In [38]:
#Reading PDF
import PyPDF2 as p
path = 'C:\\Users\\Mirnalini\\Parent\\Child1\\a.pdf'
#pdf obj
pdob = open(path,'rb')
#read obj
read = p.PdfFileReader(pdob)
#page obj
pg = read.getPage(0)
#access data
print(pg.extractText())


#writing PDF
writ = p.PdfFileWriter()
writ.addPage(pg)
pdob2 = open('aa.pdf','wb')
writ.write(pdob2)

ContentPart 1: Introduction
Part 2: 5-Step Action Plan
Part 3: Eating Schedule
Part 4: Meal Plans

In [8]:
import pandas as pd
from numpy.random import randn
import random
random.seed(10)
data = randn(5,4)
#data
rw = [1,2,3,4,5]
col= ['A','B','C','D']
df = pd.DataFrame(data,index=rw,columns=col)
df

          A         B         C         D
1  1.371992 -1.717189 -0.929011  0.229043
2 -0.210539  1.300182 -1.219788  1.791272
3 -0.675609 -0.421228 -0.636617  1.982388
4  0.120793 -0.545527 -0.577896  1.423354
5  0.564386  1.128747 -1.032969 -1.328620

In [46]:
df.iloc[[2]]

          A         B         C         D
3  0.035055 -0.313249 -1.443231 -0.172783

In [64]:
df[(df['A']<0.03) | (df['B']<1.7) ]

          A         B         C         D
1  1.454511 -1.302205  0.610355  0.461871
3  0.035055 -0.313249 -1.443231 -0.172783
4  1.100998 -0.566706  0.595448 -0.375948
5 -0.435445 -0.038281 -0.132019  0.984932

In [68]:
df = df.reset_index(drop=True)
df

          A         B         C         D
0  1.454511 -1.302205  0.610355  0.461871
1  0.535363  1.793364  1.292815 -0.932804
2  0.035055 -0.313249 -1.443231 -0.172783
3  1.100998 -0.566706  0.595448 -0.375948
4 -0.435445 -0.038281 -0.132019  0.984932

In [84]:
l1= ['A','A','A','B','B','B','C','C','C']
l2 =[1,2,3,1,2,3,1,2,3]
l3 = [1,2,3,4,5,6,7,8,9]
ind = list(zip(l1,l2,l3))
ind = pd.MultiIndex.from_tuples(ind)
ind1 = pd.MultiIndex.from_tuples(ind)
indx = pd.DataFrame(data = np.round(randn(9,4)),index=ind1,columns=['one','Two','Three','Four'])
indx

       one  Two  Three  Four
A 1 1 -2.0 -0.0    0.0  -1.0
  2 2  1.0 -0.0   -1.0  -1.0
  3 3  3.0  1.0    0.0  -0.0
B 1 4 -1.0  1.0    0.0  -1.0
  2 5  1.0 -1.0   -2.0   1.0
  3 6  1.0  0.0   -1.0   1.0
C 1 7  0.0 -1.0    1.0  -0.0
  2 8  0.0  0.0   -1.0   0.0
  3 9  0.0  1.0   -1.0  -1.0

In [7]:
import pandas as pd
df1 = pd.DataFrame({'K1':['K0','K8','K9','K5'],
                    'A1' :['A0','A8','A9','A5'],
                    'B1' :['B0','B8','B9','B5'],
                    'C1' :['C0','C8','C9','C5']
                     })
df1

   K1  A1  B1  C1
0  K0  A0  B0  C0
1  K8  A8  B8  C8
2  K9  A9  B9  C9
3  K5  A5  B5  C5

In [9]:
df2 = pd.DataFrame({'K2':['K0','K3','K1','K5'],
                    'A2' :['A0','A7','A9','A5'],
                    'B2' :['B0','B8','B9','B0'],
                    'C2' :['C1','C8','C1','C3']
                     })
df2

   K2  A2  B2  C2
0  K0  A0  B0  C1
1  K3  A7  B8  C8
2  K1  A9  B9  C1
3  K5  A5  B0  C3

In [10]:
df3 = pd.DataFrame({'K3':['K1','K3','K1','K3'],
                    'A3' :['A1','A7','A9','A3'],
                    'B3' :['B2','B7','8B','B1'],
                    'C3' :['C2','C9','C2','C4']
                     })
df3

   K3  A3  B3  C3
0  K1  A1  B2  C2
1  K3  A7  B7  C9
2  K1  A9  8B  C2
3  K3  A3  B1  C4

In [28]:
c = pd.concat([df1,df2,df3])
c

C:\Users\Mirnalini\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

    A1   A2   A3   B1   B2   B3   C1   C2   C3   K1   K2   K3
0   A0  NaN  NaN   B0  NaN  NaN   C0  NaN  NaN   K0  NaN  NaN
1   A8  NaN  NaN   B8  NaN  NaN   C8  NaN  NaN   K8  NaN  NaN
2   A9  NaN  NaN   B9  NaN  NaN   C9  NaN  NaN   K9  NaN  NaN
3   A5  NaN  NaN   B5  NaN  NaN   C5  NaN  NaN   K5  NaN  NaN
0  NaN   A0  NaN  NaN   B0  NaN  NaN   C1  NaN  NaN   K0  NaN
1  NaN   A7  NaN  NaN   B8  NaN  NaN   C8  NaN  NaN   K3  NaN
2  NaN   A9  NaN  NaN   B9  NaN  NaN   C1  NaN  NaN   K1  NaN
3  NaN   A5  NaN  NaN   B0  NaN  NaN   C3  NaN  NaN   K5  NaN
0  NaN  NaN   A1  NaN  NaN   B2  NaN  NaN   C2  NaN  NaN   K1
1  NaN  NaN   A7  NaN  NaN   B7  NaN  NaN   C9  NaN  NaN   K3
2  NaN  NaN   A9  NaN  NaN   8B  NaN  NaN   C2  NaN  NaN   K1
3  NaN  NaN   A3  NaN  NaN   B1  NaN  NaN   C4  NaN  NaN   K3

In [27]:
d = pd.merge(df1,df2,how='outer',left_on='K1', right_on='K2')
d

    K1   A1   B1   C1   K2   A2   B2   C2
0   K0   A0   B0   C0   K0   A0   B0   C1
1   K8   A8   B8   C8  NaN  NaN  NaN  NaN
2   K9   A9   B9   C9  NaN  NaN  NaN  NaN
3   K5   A5   B5   C5   K5   A5   B0   C3
4  NaN  NaN  NaN  NaN   K3   A7   B8   C8
5  NaN  NaN  NaN  NaN   K1   A9   B9   C1

In [6]:
import pandas as pd
e = pd.
e

AttributeError: module 'pandas' has no attribute 'Join'

In [24]:
import numpy as np
df['AA'] = df['A'].apply(lambda i : np.log(i))
df['BB'] = df['B'].apply(lambda i : np.square(i))
df

          A         B         C         D        AA        BB
1  1.371992 -1.717189 -0.929011  0.229043  0.316264  2.948738
2 -0.210539  1.300182 -1.219788  1.791272       NaN  1.690473
3 -0.675609 -0.421228 -0.636617  1.982388       NaN  0.177433
4  0.120793 -0.545527 -0.577896  1.423354 -2.113676  0.297600
5  0.564386  1.128747 -1.032969 -1.328620 -0.572017  1.274070

In [2]:
import pandas as pd
nin = pd.read_csv('https://raw.githubusercontent.com/PramodShenoy/911-Calls/master/911.csv',sep=',')
nin

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [83]:
nin.describe()

                lat           lng           zip        e          lat1
count  99492.000000  99492.000000  86637.000000  99492.0  99492.000000
mean      40.159526    -75.317464  19237.658298      1.0     39.984984
std        0.094446      0.174826    345.344914      0.0      0.127587
min       30.333596    -95.595595  17752.000000      1.0     30.000000
25%       40.100423    -75.392104  19038.000000      1.0     40.000000
50%       40.145223    -75.304667  19401.000000      1.0     40.000000
75%       40.229008    -75.212513  19446.000000      1.0     40.000000
max       41.167156    -74.995041  77316.000000      1.0     41.000000

In [84]:
a = nin.dtypes[nin.dtypes == 'object']
a.describe()
nin.dtypes

lat          float64
lng          float64
desc          object
zip          float64
title         object
timeStamp     object
twp           object
addr          object
e              int64
lat1           int64
dtype: object

In [86]:
nin['lat'].apply(lambda i : int(i)) 
nin

,lat,lng,desc,zip,title,timeStamp,twp,addr,e,lat1
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1,40
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1,40
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1,40
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1,40
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1,40
5,40.253473,-75.283245,CANNON AVE & W 9TH ST; LANSDALE; Station 345;...,19446.0,EMS: HEAD INJURY,2015-12-10 17:40:01,LANSDALE,CANNON AVE & W 9TH ST,1,40
6,40.182111,-75.127795,LAUREL AVE & OAKDALE AVE; HORSHAM; Station 35...,19044.0,EMS: NAUSEA/VOMITING,2015-12-10 17:40:01,HORSHAM,LAUREL AVE & OAKDALE AVE,1,40
7,40.217286,-75.405182,COLLEGEVILLE RD & LYWISKI RD; SKIPPACK; Stati...,19426.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:40:01,SKIPPACK,COLLEGEVILLE RD & LYWISKI RD,1,40
8,40.289027,-75.399590,MAIN ST & OLD SUMNEYTOWN PIKE; LOWER SALFORD;...,19438.0,EMS: SYNCOPAL EPISODE,2015-12-10 17:40:01,LOWER SALFORD,MAIN ST & OLD SUMNEYTOWN PIKE,1,40
9,40.102398,-75.291458,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD; PLYM...,19462.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,PLYMOUTH,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD,1,40
10,40.231990,-75.251891,RT202 PKWY & KNAPP RD; MONTGOMERY; 2015-12-10 ...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,MONTGOMERY,RT202 PKWY & KNAPP RD,1,40
11,40.084161,-75.308386,BROOK RD & COLWELL LN; PLYMOUTH; 2015-12-10 @ ...,19428.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,PLYMOUTH,BROOK RD & COLWELL LN,1,40
12,40.174131,-75.098491,BYBERRY AVE & S WARMINSTER RD; UPPER MORELAND;...,19040.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MORELAND,BYBERRY AVE & S WARMINSTER RD,1,40
13,40.062974,-75.135914,OLD YORK RD & VALLEY RD; CHELTENHAM; 2015-12-1...,19027.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,CHELTENHAM,OLD YORK RD & VALLEY RD,1,40
14,40.097222,-75.376195,SCHUYLKILL EXPY & CROTON RD UNDERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MERION,SCHUYLKILL EXPY & CROTON RD UNDERPASS,1,40
15,40.223778,-75.235399,STUMP RD & WITCHWOOD DR; MONTGOMERY; 2015-12-1...,18936.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,MONTGOMERY,STUMP RD & WITCHWOOD DR,1,40
16,40.243258,-75.286552,SUSQUEHANNA AVE & W MAIN ST; LANSDALE; Statio...,19446.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:46:01,LANSDALE,SUSQUEHANNA AVE & W MAIN ST,1,40
17,40.312181,-75.574260,CHARLOTTE ST & MILES RD; NEW HANOVER; Station...,19525.0,EMS: DIZZINESS,2015-12-10 17:47:01,NEW HANOVER,CHARLOTTE ST & MILES RD,1,40
18,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; Station 308A; ...,19401.0,EMS: VEHICLE ACCIDENT,2015-12-10 17:47:01,NORRISTOWN,PENN ST & ARCH ST,1,40
19,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:47:02,HORSHAM,COUNTY LINE RD & WILLOW DR,1,40
20,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; 2015-12-10 @ 17...,19401.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:47:02,NORRISTOWN,PENN ST & ARCH ST,1,40
21,40.117948,-75.209848,CHURCH RD & REDCOAT DR; WHITEMARSH; 2015-12-10...,19031.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:57:02,WHITEMARSH,CHURCH RD & REDCOAT DR,1,40
22,40.199006,-75.300058,LILAC CT & PRIMROSE DR; UPPER GWYNEDD; 2015-12...,19446.0,Fire: APPLIANCE FIRE,2015-12-10 18:02:01,UPPER GWYNEDD,LILAC CT & PRIMROSE DR,1,40
23,40.143326,-75.422819,RT422 & PAWLINGS RD OVERPASS; LOWER PROVIDENC...,NaN,Traffic: DISABLED VEHICLE -,2015-12-10 18:02:02,LOWER PROVIDENCE,RT422 & PAWLINGS RD OVERPASS,1,40
24,40.153268,-75.189558,SUMMIT AVE & RT309 UNDERPASS; UPPER DUBLIN; 20...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:02:02,UPPER DUBLIN,SUMMIT AVE & RT309 UNDERPASS,1,40
25,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROV...,19403.0,EMS: GENERAL WEAKNESS,2015-12-10 18:06:25,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,40
26,40.155283,-75.264230,PENLLYN BLUE BELL PIKE & VILLAGE CIR; WHITPAI...,19422.0,EMS: HEAD INJURY,2015-12-10 18:06:25,WHITPAIN,PENLLYN BLUE BELL PIKE & VILLAGE CIR,1,40
27,40.028903,-75.351822,EDENTON PL & DURHAM DR; DELAWARE COUNTY; 2015-...,19085.0,Fire: CARBON MONOXIDE DETECTOR,2015-12-10 18:06:25,DELAWARE COUNTY,EDENTON PL & DURHAM DR,1,40
28,40.097222,-75.376195,SCHUYLKILL EXPY & WEADLEY RD OVERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:06:26,UPPER MERION,SCHUYLKILL EXPY & WEADLEY RD OVERPASS,1,40
29,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 18:11:01,HORSHAM,COUNTY LINE RD & WILLOW DR,1,40
...,...,...,...,...,...,...,...,...,...,...
99462,40.274137,-75.660469,UPLAND SQUARE DR & SELL RD; WEST POTTSGROVE; ...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:41:00,WEST POTTSGROVE,UPLAND SQUARE DR & SELL RD,1,40
99463,40.254768,-75.660459,SHOEMAKER RD & ROBINSON ST; POTTSTOWN; Statio...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:42:00,POTTSTOWN,SHOEMAKER RD & ROBINSON ST,1,40
99464,40.163730,-75.082753,KAREN LN & BYBERRY RD; UPPER MORELAND; Statio...,19040.0,EMS: FALL VICTIM,2016-08-24 09:51:06,UPPER MORELAND,KAREN LN & BYBERRY RD,1,40
99465,40.114928,-75.340307,AIRY ST & GREEN ST; NORRISTOWN; Station 308A;...,19401.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 09:56:13,NORRISTOWN,AIRY ST & GREEN ST,1,40
99466,40.159820,-75.288436,WENTZ RD & SILO CIR; WHITPAIN; Station 385; 2...,19422.0,EMS: NAUSEA/VOMITING,2016-08-24 10:01:00,WHITPAIN,WENTZ RD & SILO CIR,1,40
99467,40.255271,-75.340722,WOODS DR & DETWILER RD; TOWAMENCIN; Station 3...,19446.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:12:01,TOWAMENCIN,WOODS DR & DETWILER RD,1,40
99468,40.088355,-75.382100,DEKALB PIKE & ALLENDALE RD; UPPER MERION; 2016...,19406.0,Fire: FIRE ALARM,2016-08-24 10:12:01,UPPER MERION,DEKALB PIKE & ALLENDALE RD,1,40
99469,40.123868,-75.341678,MARKLEY ST & JAMES ST; NORRISTOWN; 2016-08-24 ...,19401.0,Fire: FIRE ALARM,2016-08-24 10:12:01,NORRISTOWN,MARKLEY ST & JAMES ST,1,40
99470,40.185798,-75.536484,WALNUT ST & S 5TH AVE; ROYERSFORD; Station 32...,19468.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:17:01,ROYERSFORD,WALNUT ST & S 5TH AVE,1,40
99471,40.000763,-75.279769,WYNNEWOOD RD & W OLD WYNNEWOOD RD; LOWER MERI...,19096.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:17:01,LOWER MERION,WYNNEWOOD RD & W OLD WYNNEWOOD RD,1,40
99472,40.129398,-75.332213,PINE ST & W ROBERTS ST; NORRISTOWN; Station 3...,19401.0,EMS: CARDIAC EMERGENCY,2016-08-24 10:22:00,NORRISTOWN,PINE ST & W ROBERTS ST,1,40
99473,40.133533,-75.056460,BUCK RD & WAVERLY LN; BRYN ATHYN; Station 355...,19009.0,EMS: GENERAL WEAKNESS,2016-08-24 10:27:01,BRYN ATHYN,BUCK RD & WAVERLY LN,1,40
99474,40.078678,-75.086943,HUNTINGDON PIKE & FILLMORE ST; ROCKLEDGE; Sta...,19046.0,EMS: SEIZURES,2016-08-24 10:27:01,ROCKLEDGE,HUNTINGDON PIKE & FILLMORE ST,1,40
99475,40.133715,-75.229630,SHEAFF LN & WHITEMARSH VALLEY RD; WHITEMARSH; ...,19034.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:32:01,WHITEMARSH,SHEAFF LN & WHITEMARSH VALLEY RD,1,40
99476,40.257820,-75.624294,PARK DR & N ADAMS ST; POTTSTOWN; Station 329;...,19464.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:47:00,POTTSTOWN,PARK DR & N ADAMS ST,1,40
99477,40.095652,-75.244877,FOX HOUND DR & MARBLE HL; WHITEMARSH; Station...,19444.0,EMS: SUBJECT IN PAIN,2016-08-24 10:47:00,WHITEMARSH,FOX HOUND DR & MARBLE HL,1,40
99478,40.100344,-75.293955,CHEMICAL RD & GALLAGHER RD; PLYMOUTH; 2016-08-...,19462.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:47:02,PLYMOUTH,CHEMICAL RD & GALLAGHER RD,1,40
99479,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: CARDIAC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,40
99480,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIABETIC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,40
99481,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIZZINESS,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,40
99482,40.340072,-75.591709,RT100 SB & E PHILADELPHIA AVE OVERPASS; DOUGLA...,NaN,Traffic: DISABLED VEHICLE -,2016-08-24 10:52:03,DOUGLASS,RT100 SB & E PHILADELPHIA AVE OVERPASS,1,40
99483,40.084465,-75.390173,DEKALB PIKE & KING OF PRUSSIA RD; UPPER MERIO...,19406.0,EMS: BACK PAINS/INJURY,2016-08-24 10:57:00,UPPER MERION,DEKALB PIKE & KING OF PRUSSIA RD,1,40
99484,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROVI...,19403.0,Fire: FIRE ALARM,2016-08-24 10:57:00,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,40
99485,40.143601,-75.427877,EAGLEVILLE RD & REDTAIL RD; LOWER PROVIDENCE; ...,19403.0,Traffic: DISABLED VEHICLE -,2016-08-24 10:57:01,LOWER PROVIDENCE,EAGLEVILLE RD & REDTAIL RD,1,40
99486,40.179225,-75.180572,WELSH RD & NORRISTOWN RD; HORSHAM; 2016-08-24 ...,19044.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:02:02,HORSHAM,WELSH RD & NORRISTOWN RD,1,40
99487,40.132869,-75.333515,MARKLEY ST & W LOGAN ST; NORRISTOWN; 2016-08-2...,19401.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:06:00,NORRISTOWN,MARKLEY ST & W LOGAN ST,1,40
99488,40.006974,-75.289080,LANCASTER AVE & RITTENHOUSE PL; LOWER MERION; ...,19003.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:07:02,LOWER MERION,LANCASTER AVE & RITTENHOUSE PL,1,40
99489,40.115429,-75.334679,CHESTNUT ST & WALNUT ST; NORRISTOWN; Station ...,19401.0,EMS: FALL VICTIM,2016-08-24 11:12:00,NORRISTOWN,CHESTNUT ST & WALNUT ST,1,40
99490,40.186431,-75.192555,WELSH RD & WEBSTER LN; HORSHAM; Station 352; ...,19002.0,EMS: NAUSEA/VOMITING,2016-08-24 11:17:01,HORSHAM,WELSH RD & WEBSTER LN,1,40
99491,40.207055,-75.317952,MORRIS RD & S BROAD ST; UPPER GWYNEDD; 2016-08...,19446.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:17:02,UPPER GWYNEDD,MORRIS RD & S BROAD ST,1,40

In [100]:
nin.groupby(by ='zip')

In [108]:
%time

Wall time: 0 ns